#!/bin/bash

SCRIPTPATH=$(dirname $(realpath $0))
$SCRIPTPATH/down

leftwm command "LoadTheme $SCRIPTPATH/theme.toml"

setxkbmap de
xrandr --output HDMI-1 --left-of DVI-D-2 --auto
/usr/bin/polybar -c /etc/polybar/polybar.conf -q &
picom -D3 -b

